config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  root to: "items#index"
  
  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    #:title, :body
    has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord
   #:item_id, :cart_id, :quantity
    has_many   :positions
    belongs_to :user 
    has_many   :items, through: :positions
    
end

app/models/comment.rb
class Comment < ApplicationRecord
    #:body, :user_id, :commentable_id, :commentable_type 
    belongs_to :user
    belongs_to :commentable, polimorphic: true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :price, numericality: {greater_than: 0, allow_nil: true}
  validates :name,  presence: true

  has_many :positions
  has_many :carts, through: :positions

  has_many :comments, as: :commentable
  
end

app/models/order.rb
class Order < ApplicationRecord
    #:user, :user_id
    belongs_to :user
end

app/models/position.rb
class Position < ApplicationRecord
    belongs_to :item
    belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_one  :cart
has_many :orders
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

        def check_if_admin
            render_403 unless params[:admin]
        end
   

        def render_403
            render file: "public/403.html", status: 403
        end

        def render_404
            render file: "public/404.html", status: 404
        end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]

    def index
        @items = Item.all
    end

    def expensive
      @items = Item.where("price > 500")
      render "index"
    end

    # /items/1 GET
    def show
      unless @item  #=  Item.where(id: params[:id]).first
        render plain: "Page not found", status: 404
      end
    end
    # /items/new GET
    def new
      @item = Item.new
    end
    # /items/1/edit GET
    def edit
    end
    # /items POST
    def create
        @item = Item.create(item_params)
        if @item.errors.empty?
          redirect_to item_path(@item)
        else
          render "new"
        end
    end
    # /items/1 PUT
    def update
      #@item = Item.find(params[:id])
      @item.update_attributes(item_params)
      if @item.errors.empty?
         redirect_to item_path(@item)
      else
        render "edit"
      end
    end
    # /items/1 DELETE
    def destroy
      #@item = Item.destroy(params[:id])
      @item.destroy
      redirect_to action: "index"
    end

    def upvote
      @item.increment!(:votes_count)
      redirect_to action: :index
    end

    

  private

    def item_params
      params.require(:item).permit(:price, :name, :real, :weight, :description)
    end # add do user controller
    
    def find_item
      @item = Item.where(id: params[:id]).first
      render_404 unless @item
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<p>Ціна: <br/><%= f.text_field :price %></p>
<p>Назва: <br/><%= f.text_field :name %></p>
<p>Опис: <br/><%= f.text_field :description %></p>
<p>Вага: <br/><%= f.text_field :weight %></p>

app/views/items/edit.html.erb
<h1>Edit item</h1>
  <%= form_for @item do |f| %>
    
    <%= render partial: "form", locals: {f: f}%>

    <p><%= f.submit "Зберегти товар" %></p>
  <% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
<b>No items in the shop</b>
<% else %>
<table>
    <tr> 
        <th>item id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Видалення</th>
        <th>Рейтинг</th>
    </tr>  
    <% end %>
<% @items.each do |i| %>
    <tr> 
        <td><%= i.id %></td>
        <td><%=link_to i.name, item_path(i) %></td>
        <td><%= i.price %> грн</td>
        <td><%= link_to "Видалити", i, method: :delete, 
            data: {confirm: "Ви впевнені, що хочете видалити?"} %></td>
        <td>Рейтинг: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i)%></td>
    </tr>

<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>
  <%= form_for @item do |f| %>
    <p>Ціна: <br/><%= f.text_field :price %></p>
    <p>Назва: <br/><%= f.text_field :name %></p>
    <p>Опис: <br/><%= f.text_field :description %></p>
    <p>Вага: <br/><%= f.text_field :weight %></p>

    <p><%= f.submit "Створити товар" %></p>
  <% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<ul>
  <li><%= @item.price %> грн.</li>
  <li><%= @item.description %></li>
  <li>Вага: <%= @item.weight %> кг.</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
        
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/shared/_email.html.erb
<h3>Технічні питання: biosoln91@gmail.com</h3>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>